name: Terraform CI/CD

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    # Ajout des variables d'environnement pour le job
    env:
      TF_VAR_container_name: ${{ secrets.TF_VAR_container_name }}
      TF_VAR_external_port: ${{ secrets.TF_VAR_external_port }}
      TF_VAR_nginx_tag: ${{ secrets.TF_VAR_nginx_tag }}

    steps:
      - name: 1. Checkout du code
        uses: actions/checkout@v4

      - name: 2. Installation de Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.5

      - name: 3. Vérification du format
        run: terraform fmt -check

      - name: 4. Initialisation du projet
        run: terraform init

      - name: 5. Validation du plan
        # Plus besoin de -var-file, Terraform lit l'environnement
        run: terraform plan

      - name: 6. Application
        # Plus besoin de -var-file
        run: terraform apply -auto-approve

      - name: 7. Bonus - Vérification Docker
        run: docker ps